# Generated by Django 4.2 on 2024-09-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about1_about2_about3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=200)),
                ('customers', models.CharField(max_length=200)),
                ('projects', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
            ],
        ),
    ]
